### ISSUE TITLE
Submission tarball creation broken

### ISSUE THREAD

**Issue by Hexadecimaaal** [mlcommons/cm4mlperf-inference#77]
I followed the instructions in https://scc24-benchmarking.readthedocs.io/en/latest/benchmarks/mlperf.html for the SCC24 competition. Everything before the "Submission Commands" section ran, and I have collected the outputs, but the "Generate actual submission tree" section fails with the following error:
```
Traceback (most recent call last):   File "/global_raid/CM_hex/repos/local/cache/7e391d7d3e244f58/inference/tools/submission/preprocess_submission.py", line 546, in <module>     sys.exit(main())   File "/global_raid/CM_hex/repos/local/cache/7e391d7d3e244f58/inference/tools/submission/preprocess_submission.py", line 537, in main     infer_scenario_results(args, config)   File "/global_raid/CM_hex/repos/local/cache/7e391d7d3e244f58/inference/tools/submission/preprocess_submission.py", line 406, in infer_scenario_results     clean_invalid_results(   File "/global_raid/CM_hex/repos/local/cache/7e391d7d3e244f58/inference/tools/submission/preprocess_submission.py", line 259, in clean_invalid_results     shutil.rmtree(scenario_compliance_path)   File "/usr/lib64/python3.9/shutil.py", line 724, in rmtree     onerror(os.lstat, path, sys.exc_info())   File "/usr/lib64/python3.9/shutil.py", line 722, in rmtree     orig_st = os.lstat(path) FileNotFoundError: [Errno 2] No such file or directory: 'open/loyly/compliance/o184i072-reference-rocm-pytorch-v2.6.0.dev20241118-scc24-base/stable-diffusion-xl/offline'
```

My command used was:
```
cm run script --tags=generate,inference,submission    --clean    --preprocess_submission=yes       --tar=yes    --env.CM_TAR_OUTFILE=submission.tar.gz    --division=open    --category=datacenter    --env.CM_DETERMINE_MEMORY_CONFIGURATION=yes    --run_style=test    --adr.submission-checker.tags=_short-run    --quiet    --submitter=loyly
```

**Comment by arjunsuresh** [comment]
Can you please remove `--preprocess_submission=yes` from the command and retry? It was already removed in the docs but got replaces by some PR. It is fixed again: https://docs.mlcommons.org/inference/benchmarks/text_to_image/reproducibility/scc24/#__tabbed_4_2

**Comment by Hexadecimaaal** [comment]
(the competition is over and this issue is not relevant anymore.)
